name = "Reveal Positions"
version = 1
copyright = "Myxir"
description = "Reveals starting locations of players"
author = "Myxir"
url = ""
uid = "b0d9ac94-c5e6-11e5-9912-ba0be0483c18"
exclusive = false
ui_only = true
conflicts = {}
