name = "M&B"
uid = "62e2j64a-53a1-y6sl-32h5-146as576a18u4"
version = 0.5
description = "Mickvini and Bobichka Mod Pack For Supreme"
author = "Bobichka, Mickvini"
--icon = ""
selectable = true
enabled = true
exclusive = false
ui_only = false
before = { }
after = { }
