name = "Advanced Selection Info"
version = 2
copyright = ""
description = "Version 2. Fixed build power of ACU. Display total DPS, HP, build power, mass cost and energy cost of selected units. This mod is based on Selection Cost UI. If you discover bug please tell me: dentolm6@gmail.com"
author = "anden"
url = ""
uid = "a5d6378a-0ade-47d2-8ff5-eb5a89c7d3b4"
icon = "/mods/Advanced Selection Info/icon.png"
exclusive = false
ui_only = true