##****************************************************************************
#**  File     :  lua/ui/help/unitdescriptions.lua
#**  Author(s):  Exavier Macbeth
#**
#**
#****************************************************************************
 
##Exavier's Units

do
Tooltips["exstealth_toggle"] = {
    title = "<LOC tooltipui0981>Active Jammer Subsystem",
    description = "<LOC tooltipui0982>Toggles on the combination blip generator and personal stealth system on or off",
}
Tooltips["excloak_toggle"] = {
    title = "<LOC tooltipui0983>Stealth Subsystem",
    description = "<LOC tooltipui0984>Toggle the advanced stealth suite on or off.",
}
Tooltips["exjammer_toggle"] = {
    title = "<LOC tooltipui0985>Radar Jamming Subsystem",
    description = "<LOC tooltipui0986>Toggle the radar blip generator on or off.",
}
Tooltips['EXScryTarget'] = {
   title = "<LOC tooltipui0987>Scry Targetting",
   description = "<LOC tooltipui0988>Target Area for Scrying",
}

end

-- === M28AI hook merged (was separate M28AI mod; paths rewritten in Phase 2) ===
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 23/08/2024 22:25
---
Tooltips['M28Toggle'] = {
    title = "Toggle M28AI logic",
    description = "Turns M28AI logic on/off for the unit",
}