---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 10/06/2023 20:25
---
---

--Thanks to Jip who provided the below code as part of the FAF changes to how brains are handled
local StandardBrain = import("/lua/aibrain.lua").AIBrain
local M28Events = import('/mods/M&B/lua/AI/M28Events.lua')

NewAIBrain = Class(StandardBrain) {

    OnBeginSession = function(self)
        StandardBrain.OnBeginSession(self)
        import('/mods/M&B/lua/AI/M28Overseer.lua').bBeginSessionTriggered = true
    end,

    OnDefeat = function(self)
        StandardBrain.OnDefeat(self)
        ForkThread(M28Events.OnPlayerDefeated, self)

    end,

    OnCreateAI = function(self, planName)
        StandardBrain.OnCreateAI(self)
        --LOG('M28AI brain class OnCreateAI triggered, brain nickname='..self.Nickname)
        self.M28AI = true
        import('/mods/M&B/lua/AI/M28Utilities.lua').bM28AIInGame = true
        ForkThread(M28Events.OnCreateBrain, self, planName, false)
        --M&B roster thread fork lives in hook/lua/aibrain.lua OnCreateAI instead: NewAIBrain.OnCreateAI doesnt fire in the Steam/M&B setup (the hook's AIBrain override is the active path, per the 'Brain OnCreateAI ... personality medium' log), and IsMBModActive cant be called here anyway (__blueprints isnt populated when OnCreateAI fires).
    end,

    OnCreateHuman = function(self, planName) --This doenst actually trigger; instead need a hook of simInit.lua
        StandardBrain.OnCreateHuman(self, planName)
        ForkThread(M28Events.OnCreateBrain, self, planName, true)
    end,

}